const ActionTypes = {
  Home: {
    GET_IMAGE_LIST: "GET_IMAGE_LIST",
  },
  Common: {
    REQUEST_ERROR_STATUS: "REQUEST_ERROR_STATUS",
    RESPONSE_ERROR_STATUS: "RESPONSE_ERROR_STATUS",
    REPORT_UNHANDLED_ERROR: "REPORT_UNHANDLED_ERROR",
  },
  SchoolOnboarding: {
    SAVE_SCHOOL_ONBOARDING: "SAVE_SCHOOL_ONBOARDING",
  },
  AddressInfo: {
    GET_COUNTRY_LIST: "GET_COUNTRY_LIST",
    GET_STATE_LIST: "GET_STATE_LIST",
    GET_CITY_LIST: "GET_CITY_LIST",
  },
};

export default ActionTypes;
